<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_header-slide-fields',
		'title' => 'Header Slide Fields',
		'fields' => array (
			array (
				'key' => 'field_53e17dfe42c8c',
				'label' => 'Action Link Title',
				'name' => 'action_link_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'headerslides',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_home-page-columns',
		'title' => 'Home Page Columns',
		'fields' => array (
			array (
				'key' => 'field_539a1b273f741',
				'label' => 'Highlight Columns',
				'name' => 'highlight_columns',
				'type' => 'flexible_content',
				'layouts' => array (
					array (
						'label' => '3 Column Row',
						'name' => '3_column_row',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_53e424fe47724',
								'label' => 'Column 1 Title',
								'name' => '3_column_1_text',
								'type' => 'text',
								'required' => 1,
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_539a1b763f742',
								'label' => 'Column 1',
								'name' => 'column_1',
								'type' => 'wysiwyg',
								'column_width' => 33,
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_53e4253147725',
								'label' => 'Column 2 Title',
								'name' => '3_column_2_text',
								'type' => 'text',
								'required' => 1,
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_539a1bd73f744',
								'label' => 'Column 2',
								'name' => 'column_2',
								'type' => 'wysiwyg',
								'column_width' => 33,
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_53e4254847726',
								'label' => 'Column 3 Title',
								'name' => '3_column_3_text',
								'type' => 'text',
								'required' => 1,
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_539a1bdf3f745',
								'label' => 'Column 3',
								'name' => 'column_3',
								'type' => 'wysiwyg',
								'column_width' => 33,
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
						),
					),
					array (
						'label' => '2 Column Row',
						'name' => '2_column_row',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_53e17045cf95a',
								'label' => 'Column 1 Image',
								'name' => 'column_1_image_1',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'id',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_53a0249d6cb78',
								'label' => 'Column 1 Title',
								'name' => 'column_1_title_1',
								'type' => 'text',
								'required' => 1,
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53a01f151d33e',
								'label' => 'Column 1',
								'name' => 'column_1_text',
								'type' => 'wysiwyg',
								'column_width' => 33,
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_53e17077cf95b',
								'label' => 'Column 2 Image',
								'name' => 'column_2_image_1',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'id',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_53a024b36cb79',
								'label' => 'Column 2 Title',
								'name' => 'column_2_title_1',
								'type' => 'text',
								'required' => 1,
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53a0204d09f12',
								'label' => 'Column 2 Content Options',
								'name' => 'content_options',
								'type' => 'select',
								'instructions' => 'Select the type of content you would like to place here.',
								'required' => 1,
								'column_width' => '',
								'choices' => array (
									'text' => 'Text',
									'events' => 'Events',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_53a01f151d33f',
								'label' => 'Column 2',
								'name' => 'column_2_text',
								'type' => 'wysiwyg',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_53a0204d09f12',
											'operator' => '==',
											'value' => 'text',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => 33,
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_53a020ea09f13',
								'label' => 'Events Title',
								'name' => 'events_title',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_53a0204d09f12',
											'operator' => '==',
											'value' => 'events',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
					),
				),
				'button_label' => 'Add Row',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-hometemplate.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-hometemplate2.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'tags',
				11 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}

